### ISSUE TITLE
mac版本不能下载

### ISSUE THREAD

**Issue by colin-chang** [rangaofei/SSokit-qmake#3]
{"code":3501,"msg":{"share_download_over_limit":"当前资源下载超过限制"}}

**Comment by rangaofei** [comment]
https://coding.net/u/rgf456/p/SSokit/git/raw/master/v1.0.5/SSokit.dmg
试试这个链接，coding的分享文件有限制次数。github下载太慢了，所以挂在的coding上

**Comment by colin-chang** [comment]
可以。这个小工具简单好用，要支持下
