### ISSUE TITLE
Missing version number in 1.1.9

### ISSUE THREAD

**Issue by suschizu** [rangaofei/SSokit-qmake#34]
Hello - the SSokit download  1.1.9 doesn't contain a version number (https://github.com/rangaofei/SSokit-qmake/releases/download/1.1.9/SSokit_1.1.9.dmg) - BundleVersion and ShortVersionString is empty 

see:
<img width="322" alt="Screen Shot 2021-12-18 at 16 09 09" src="https://user-images.githubusercontent.com/16004333/146645801-d7c1775b-028b-4886-a97a-7c1140c17d01.png">

**Comment by rangaofei** [comment]
please check the new version 1.2.0

**Comment by suschizu** [comment]
great thanks - version number is contained now
