### ISSUE TITLE
服务端不能向客户端发送带有数组类型的json对象

### ISSUE THREAD

**Issue by Ldachao** [rangaofei/SSokit-qmake#41]
test：

{
  "array": [
    1,
    2,
    3
  ],
  "boolean": true,
  "null": null,
  "number": 123,
  "object": {
    "a": "b",
    "c": "d",
    "e": "f"
  },
  "string": "Hello World"
}

**Comment by rangaofei** [comment]
输入中括号时请使用`[[some text]`格式。

```
{
"array": [[
1,
2,
3
],
"boolean": true,
"null": null,
"number": 123,
"object": {
"a": "b",
"c": "d",
"e": "f"
},
"string": "Hello World"
}
```

**Comment by Ldachao** [comment]
可以的，已验证。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月10日(周四) 上午8:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rangaofei/SSokit-qmake] 服务端不能向客户端发送带有数组类型的json对象 (Issue #41)




 
输入中括号时请使用[[some text]格式。
 { "array": [[ 1, 2, 3 ], "boolean": true, "null": null, "number": 123, "object": { "a": "b", "c": "d", "e": "f" }, "string": "Hello World" }
